
OBJECTS += $(WORKSPACE_PATH)bindings/audio.o $(WORKSPACE_PATH)bindings/gsm.o $(WORKSPACE_PATH)bindings/gpio.o \
           $(WORKSPACE_PATH)bindings/i2c.o $(WORKSPACE_PATH)bindings/timer.o $(WORKSPACE_PATH)bindings/tcp.o  \
	   $(WORKSPACE_PATH)bindings/screen.o $(WORKSPACE_PATH)bindings/https.o $(WORKSPACE_PATH)bindings/bluetooth.o $(WORKSPACE_PATH)bindings/button.o
INCLUDE_PATHS += -I$(WORKSPACE_PATH)bindings